// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace inzLessons.Common.Models
{
    public partial class Allowedreservation
    {
        public int Id { get; set; }
        public DateTime Reservationdatestart { get; set; }
        public DateTime Reservationdateend { get; set; }
        public int Teacherid { get; set; }
        public int? MaxHourPerStudent { get; set; }

        public virtual Users Teacher { get; set; }
    }
}