// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace inzLessons.Common.Models
{
    public partial class Lessoncondition
    {
        public int Id { get; set; }
        public int? Allowedhourinweek { get; set; }
        public float? Price { get; set; }
        public string Configname { get; set; }
        public int Teacherid { get; set; }
    }
}