// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace inzLessons.Common.Models
{
    public partial class Lessoncondition
    {
        public Lessoncondition()
        {
            Useringroup = new HashSet<Useringroup>();
        }

        public int Id { get; set; }
        public int? Allowedhourinweek { get; set; }
        public float? Price { get; set; }
        public string Configname { get; set; }
        public int Teacherid { get; set; }

        public virtual Users Teacher { get; set; }
        public virtual ICollection<Useringroup> Useringroup { get; set; }
    }
}