// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Common.DAL.Model
{
    public class Membership
    {
        public Membership()
        {
            Users = new HashSet<Users>();
        }

        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}