// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace inzLessons.Common.Models
{
    public partial class Membership
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public int Id { get; set; }

        public virtual Users Users { get; set; }
    }
}