// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace inzLessons.Common.Models
{
    public partial class Reservationrequest
    {
        public DateTime Starttime { get; set; }
        public DateTime Endtime { get; set; }
        public bool? Isaccepted { get; set; }
        public string Description { get; set; }
        public int? Userid { get; set; }
        public int? Allowedreservationid { get; set; }
        public int Id { get; set; }

        public virtual Allowedreservation Allowedreservation { get; set; }
        public virtual Users User { get; set; }
    }
}