// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace inzLessons.Common.Models
{
    public partial class Users
    {
        public Users()
        {
            Reservation = new HashSet<Reservation>();
            Useringroup = new HashSet<Useringroup>();
        }

        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public DateTime Createdate { get; set; }
        public int? RoleId { get; set; }
        public string Username { get; set; }
        public int Id { get; set; }

        public virtual Membership IdNavigation { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual ICollection<Useringroup> Useringroup { get; set; }
    }
}