// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace inzLessons.Common.Models
{
    public partial class Useringroup
    {
        public int Userid { get; set; }
        public int Groupid { get; set; }
    }
}