// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace inzLessons.Common.Models
{
    public partial class Users
    {
        public Users()
        {
            Lessoncondition = new HashSet<Lessoncondition>();
            Lessonsgroup = new HashSet<Lessonsgroup>();
            Useringroup = new HashSet<Useringroup>();
        }

        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public DateTime Createdate { get; set; }
        public int? RoleId { get; set; }
        public string Username { get; set; }

        public virtual Membership IdNavigation { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Lessoncondition> Lessoncondition { get; set; }
        public virtual ICollection<Lessonsgroup> Lessonsgroup { get; set; }
        public virtual ICollection<Useringroup> Useringroup { get; set; }
    }
}