// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using inzLessons.Common.Models;

#nullable disable

namespace inzLessons.Common.Context
{
    public partial class InzlessonsdbContext : DbContext
    {
        public InzlessonsdbContext()
        {
        }

        public InzlessonsdbContext(DbContextOptions<InzlessonsdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Allowedreservation> Allowedreservation { get; set; }
        public virtual DbSet<Lessoncondition> Lessoncondition { get; set; }
        public virtual DbSet<Lessonsgroup> Lessonsgroup { get; set; }
        public virtual DbSet<Membership> Membership { get; set; }
        public virtual DbSet<Messagefile> Messagefile { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Reservationmessage> Reservationmessage { get; set; }
        public virtual DbSet<Reservationrequest> Reservationrequest { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Useringroup> Useringroup { get; set; }
        public virtual DbSet<Userinreservation> Userinreservation { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseNpgsql("Password=testPass123;Username=35223954_inzdb;Database=35223954_inzdb;Host=serwer2148690.home.pl");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "pl_PL.utf8");

            modelBuilder.Entity<Allowedreservation>(entity =>
            {
                entity.ToTable("allowedreservation");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.Reservationdateend).HasColumnName("reservationdateend");

                entity.Property(e => e.Reservationdatestart).HasColumnName("reservationdatestart");

                entity.Property(e => e.Teacherid).HasColumnName("teacherid");

                entity.HasOne(d => d.Teacher)
                    .WithMany(p => p.Allowedreservation)
                    .HasForeignKey(d => d.Teacherid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_allowedreservation_user");
            });

            modelBuilder.Entity<Lessoncondition>(entity =>
            {
                entity.ToTable("lessoncondition");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.Allowedhourinweek).HasColumnName("allowedhourinweek");

                entity.Property(e => e.Configname)
                    .HasMaxLength(20)
                    .HasColumnName("configname");

                entity.Property(e => e.Price).HasColumnName("price");

                entity.Property(e => e.Teacherid).HasColumnName("teacherid");
            });

            modelBuilder.Entity<Lessonsgroup>(entity =>
            {
                entity.ToTable("lessonsgroup");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.Creationdate).HasColumnName("creationdate");

                entity.Property(e => e.Description)
                    .HasMaxLength(400)
                    .HasColumnName("description");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("name");

                entity.Property(e => e.Teacherid).HasColumnName("teacherid");
            });

            modelBuilder.Entity<Membership>(entity =>
            {
                entity.ToTable("membership");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Login)
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnName("login");

                entity.Property(e => e.Password)
                    .HasMaxLength(256)
                    .HasColumnName("password");

                entity.Property(e => e.PasswordSalt)
                    .HasMaxLength(256)
                    .HasColumnName("password_salt");
            });

            modelBuilder.Entity<Messagefile>(entity =>
            {
                entity.ToTable("messagefile");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.File).HasColumnName("file");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnName("name");
            });

            modelBuilder.Entity<Reservation>(entity =>
            {
                entity.ToTable("reservation");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.Description)
                    .HasMaxLength(256)
                    .HasColumnName("description");

                entity.Property(e => e.Isonline).HasColumnName("isonline");

                entity.Property(e => e.ReservationEndDate).HasColumnName("reservationEndDate");

                entity.Property(e => e.Reservationdate).HasColumnName("reservationdate");

                entity.Property(e => e.Teacherid).HasColumnName("teacherid");

                entity.HasOne(d => d.Teacher)
                    .WithMany(p => p.Reservation)
                    .HasForeignKey(d => d.Teacherid)
                    .HasConstraintName("fk_reservation_users");
            });

            modelBuilder.Entity<Reservationmessage>(entity =>
            {
                entity.ToTable("reservationmessage");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Creationdate).HasColumnName("creationdate");

                entity.Property(e => e.Fileid).HasColumnName("fileid");

                entity.Property(e => e.Reservationid).HasColumnName("reservationid");

                entity.Property(e => e.Text)
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasColumnName("text");

                entity.Property(e => e.Userid).HasColumnName("userid");

                entity.HasOne(d => d.File)
                    .WithMany(p => p.Reservationmessage)
                    .HasForeignKey(d => d.Fileid)
                    .HasConstraintName("fk_reservationmessage_file");

                entity.HasOne(d => d.Reservation)
                    .WithMany(p => p.Reservationmessage)
                    .HasForeignKey(d => d.Reservationid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_reservationmessage_reservation");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Reservationmessage)
                    .HasForeignKey(d => d.Userid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_message_users");
            });

            modelBuilder.Entity<Reservationrequest>(entity =>
            {
                entity.ToTable("reservationrequest");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.Allowedreservationid).HasColumnName("allowedreservationid");

                entity.Property(e => e.Description)
                    .HasMaxLength(255)
                    .HasColumnName("description");

                entity.Property(e => e.Endtime)
                    .HasColumnType("date")
                    .HasColumnName("endtime");

                entity.Property(e => e.Isaccepted).HasColumnName("isaccepted");

                entity.Property(e => e.Starttime)
                    .HasColumnType("date")
                    .HasColumnName("starttime");

                entity.Property(e => e.Userid).HasColumnName("userid");

                entity.HasOne(d => d.Allowedreservation)
                    .WithMany(p => p.Reservationrequest)
                    .HasForeignKey(d => d.Allowedreservationid)
                    .HasConstraintName("fk_reservationrequest_allowedres");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Reservationrequest)
                    .HasForeignKey(d => d.Userid)
                    .HasConstraintName("fk_reservationrequest_student");
            });

            modelBuilder.Entity<Role>(entity =>
            {
                entity.ToTable("role");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnName("name");
            });

            modelBuilder.Entity<Useringroup>(entity =>
            {
                entity.HasKey(e => new { e.Userid, e.Groupid })
                    .HasName("useringroup_pkey");

                entity.ToTable("useringroup");

                entity.Property(e => e.Userid).HasColumnName("userid");

                entity.Property(e => e.Groupid).HasColumnName("groupid");

                entity.Property(e => e.Price).HasColumnName("price");

                entity.HasOne(d => d.Group)
                    .WithMany(p => p.Useringroup)
                    .HasForeignKey(d => d.Groupid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_group_useringroup");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Useringroup)
                    .HasForeignKey(d => d.Userid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_useringroup");
            });

            modelBuilder.Entity<Userinreservation>(entity =>
            {
                entity.HasKey(e => new { e.Reservationid, e.Userid, e.Groupid })
                    .HasName("userinreservation_pkey");

                entity.ToTable("userinreservation");

                entity.Property(e => e.Reservationid).HasColumnName("reservationid");

                entity.Property(e => e.Userid).HasColumnName("userid");

                entity.Property(e => e.Groupid).HasColumnName("groupid");

                entity.HasOne(d => d.Reservation)
                    .WithMany(p => p.Userinreservation)
                    .HasForeignKey(d => d.Reservationid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_userinreservation_reservation");

                entity.HasOne(d => d.Useringroup)
                    .WithMany(p => p.Userinreservation)
                    .HasForeignKey(d => new { d.Userid, d.Groupid })
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_useringroup_userinreservation");
            });

            modelBuilder.Entity<Users>(entity =>
            {
                entity.ToTable("users");

                entity.Property(e => e.Id)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id");

                entity.Property(e => e.City)
                    .HasMaxLength(100)
                    .HasColumnName("city");

                entity.Property(e => e.Createdate).HasColumnName("createdate");

                entity.Property(e => e.Email)
                    .HasMaxLength(100)
                    .HasColumnName("email");

                entity.Property(e => e.Firstname)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("firstname");

                entity.Property(e => e.Lastname)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("lastname");

                entity.Property(e => e.Phone)
                    .HasMaxLength(20)
                    .HasColumnName("phone");

                entity.Property(e => e.RoleId).HasColumnName("role_id");

                entity.Property(e => e.Username)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("username");

                entity.HasOne(d => d.IdNavigation)
                    .WithOne(p => p.Users)
                    .HasForeignKey<Users>(d => d.Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_membership_users");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.Users)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("fk_role_users");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}